version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: synergysphere-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: synergysphere
    volumes:
      - mongodb_data:/data/db
    networks:
      - synergysphere-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: synergysphere-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/synergysphere?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRE: 7d
      PORT: 5000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - synergysphere-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: synergysphere-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000
      REACT_APP_SOCKET_URL: http://localhost:5000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - synergysphere-network

volumes:
  mongodb_data:

networks:
  synergysphere-network:
    driver: bridge
